### ISSUE TITLE
Missing DaggerActivityComponent.java

### ISSUE THREAD

**Issue by jiarWang** [towavephone/MemoryCleaner#1]
It looks like that your `DaggerActivityComponent.java`  is no available anymore, could your please push it, so that i can study this project .thank you very much...

**Comment by towavephone** [comment]
I delete my project and download again by github , then I find no problem with my project after sync this project . 
Can you describe your problem more clearly? @jiarWang 
![_20180407120737](https://user-images.githubusercontent.com/13433289/38451144-4ded816c-3a5d-11e8-829a-cb3ff93b5aef.png)

**Comment by NewbyThebest** [comment]
i meet same problem。the issues is that:loss class follows:DaggerActivityComponent、DaggerAppComponent、DaggerFragmentComponent.
