### ISSUE TITLE
Android skd 7.0 8.0 ，你的这些功能还能用吗？

### ISSUE THREAD

**Issue by FSilver** [towavephone/MemoryCleaner#2]

**Comment by towavephone** [comment]
有些功能并不能，readme里面已经明确所有功能要正常运行只适用于7.0以下，不包括7.0

**Comment by towavephone** [comment]
> _No description provided._

有些功能并不能，readme里面已经明确所有功能要正常运行只适用于7.0以下，不包括7.0
